name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install Python 3.13
        run: uv python install 3.13

      - name: Install dependencies
        run: uv sync --locked

      - name: Run ruff
        run: uv run ruff check

      - name: Check prettier formatting
        run:
          npx prettier --prose-wrap always --check "./*.md" ".github/**/*.yml"
